import React, { useState } from 'react';
import { X, Shield, Scale, AlertTriangle, FileText, Lock, Globe } from 'lucide-react';
import win365Logo from '../assets/logo1.png';

const LegalPolicyModal = ({ isOpen, onClose }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/90 backdrop-blur-md animate-fade-in">
            <div className="bg-[#0a0a0a] w-full max-w-4xl max-h-[90vh] rounded-2xl border border-[#d4af37]/30 shadow-[0_0_50px_rgba(212,175,55,0.1)] flex flex-col relative overflow-hidden">

                {/* Header */}
                <div className="p-6 border-b border-white/5 flex items-center justify-between bg-gradient-to-r from-black via-[#111] to-black">
                    <div className="flex items-center gap-3">
                        <img src={win365Logo} alt="Win365" className="h-10 w-auto" />
                        <div>
                            <h2 className="text-lg md:text-xl font-serif text-[#d4af37] uppercase tracking-wide">Legal Disclaimer, Compliance & Usage Policy</h2>
                            <p className="text-[10px] text-gray-500 uppercase tracking-widest">Effective Date: January 1, 2026</p>
                        </div>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-white/5 rounded-full transition-colors group"
                    >
                        <X className="text-gray-400 group-hover:text-white" size={24} />
                    </button>
                </div>

                {/* Content - Scrollable */}
                <div className="flex-1 overflow-y-auto p-8 space-y-10 custom-scrollbar text-gray-300 leading-relaxed text-sm md:text-base text-justify">

                    {/* 1. Purpose */}
                    <section>
                        <h3 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
                            <span className="text-[#d4af37]">1.</span> Software Purpose & Nature
                        </h3>
                        <p className="mb-2">Win365 is a software-based analytical and informational platform designed to assist users in understanding probability trends, statistical patterns, and data-driven insights related to European roulette games.</p>
                        <div className="bg-red-500/10 border border-red-500/20 p-4 rounded-lg">
                            <p className="text-red-400 font-bold mb-1 flex items-center gap-2"><AlertTriangle size={16} /> Important:</p>
                            <p className="text-red-300/80 text-xs md:text-sm">Win365 is not a gambling operator, casino, betting service, or wagering platform. The software does not place bets, accept wagers, or interact directly with any gambling system. The platform functions solely as a probability analysis and decision-support tool.</p>
                        </div>
                    </section>

                    {/* 2. No Guarantee */}
                    <section>
                        <h3 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
                            <span className="text-[#d4af37]">2.</span> No Guarantee of Outcomes
                        </h3>
                        <p className="mb-2">Win365 does not guarantee winning results, accurate predictions, profits, financial gains, or consistent outcomes.</p>
                        <p className="mb-2">Roulette is a game of chance and randomness. While Win365 uses Artificial Intelligence, advanced mathematics, and statistical models, all outputs are probability-based estimations only.</p>
                        <p className="text-gray-400 italic">Any prediction or insight generated by Win365 is not a guarantee of future outcomes.</p>
                    </section>

                    {/* 3. AI Limitations */}
                    <section>
                        <h3 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
                            <span className="text-[#d4af37]">3.</span> Artificial Intelligence & Analytical Limitations
                        </h3>
                        <p className="mb-2">Win365 utilizes Artificial Intelligence combined with 29 mathematical and analytical strategies to interpret data. However:</p>
                        <ul className="list-disc pl-5 space-y-1 text-gray-400">
                            <li>AI predictions are based on historical and provided data</li>
                            <li>Random events cannot be fully predicted</li>
                            <li>Results may vary depending on input quality and game conditions</li>
                        </ul>
                        <p className="mt-2 text-xs">Users acknowledge that AI-generated insights are inherently probabilistic, not deterministic.</p>
                    </section>

                    {/* 4. User Responsibility */}
                    <section>
                        <h3 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
                            <span className="text-[#d4af37]">4.</span> User Responsibility & Assumption of Risk
                        </h3>
                        <p className="mb-2">By using Win365, the user fully understands and agrees that:</p>
                        <ul className="list-disc pl-5 space-y-1 text-gray-400 mb-4">
                            <li>All decisions made using the software are entirely at the user’s own discretion</li>
                            <li>Win365 does not influence or control user actions</li>
                            <li>The user assumes full responsibility for any financial decisions or losses</li>
                        </ul>
                        <p className="text-xs text-gray-500">Win365, its owners, developers, partners, and affiliates shall not be held responsible or liable for financial losses, missed opportunities, emotional distress, or indirect/consequential damages.</p>
                    </section>

                    {/* 5. No Liability */}
                    <section className="bg-white/5 p-4 rounded-lg">
                        <h3 className="text-lg font-bold text-white mb-2 flex items-center gap-2">
                            <span className="text-[#d4af37]">5.</span> No Liability for Losses
                        </h3>
                        <p className="text-sm text-gray-300">To the maximum extent permitted by law, Win365 is not liable for any direct or indirect losses. No compensation will be provided for losses incurred. The software is provided “as is” and “as available”. Users agree that use of Win365 is entirely at their own risk.</p>
                    </section>

                    {/* 6. Refund Policy */}
                    <section>
                        <h3 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
                            <span className="text-[#d4af37]">6.</span> Subscription & Refund Policy
                        </h3>
                        <p className="mb-2 font-bold text-white">All Win365 subscriptions are Non-refundable, Non-transferable, and Final once activated.</p>
                        <p className="mb-2 text-sm">No refunds will be issued for partial usage, dissatisfaction with results, misinterpretation of software outputs, change of mind, or losses incurred using the software. Users are encouraged to review all information before purchasing a subscription.</p>
                    </section>

                    {/* 7. Not Advisory */}
                    <section>
                        <h3 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
                            <span className="text-[#d4af37]">7.</span> Not a Financial, Gambling, or Legal Advisory Service
                        </h3>
                        <p>Win365 does not provide financial advice, investment advice, gambling advice, or legal advice. All information provided is educational and analytical only.</p>
                    </section>

                    {/* 8. Compliance - 12. Contact */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        <section>
                            <h3 className="text-base font-bold text-white mb-2"><span className="text-[#d4af37]">8.</span> Compliance With Local Laws</h3>
                            <p className="text-xs text-gray-400">Users are solely responsible for ensuring that use of Win365 complies with local laws and regulations. Accessing probability or analytical tools is permitted in their jurisdiction.</p>
                        </section>
                        <section>
                            <h3 className="text-base font-bold text-white mb-2"><span className="text-[#d4af37]">9.</span> Intellectual Property</h3>
                            <p className="text-xs text-gray-400">All content, algorithms, Al models, designs, and systems used within Win365 are the intellectual property of Win365 and AICHAINZ. Unauthorized copying or reverse engineering is prohibited.</p>
                        </section>
                        <section>
                            <h3 className="text-base font-bold text-white mb-2"><span className="text-[#d4af37]">10.</span> Modification of Policy</h3>
                            <p className="text-xs text-gray-400">Win365 reserves the right to modify this policy at any time without prior notice. Continued use of the platform constitutes acceptance of the updated policy.</p>
                        </section>
                        <section>
                            <h3 className="text-base font-bold text-white mb-2"><span className="text-[#d4af37]">11.</span> Developer & Ownership</h3>
                            <p className="text-xs text-gray-400">Win365 is developed and maintained by <strong className="text-white">AICHAINZ</strong>.</p>
                            <a href="https://www.aichainzom" className="text-[#d4af37] text-xs hover:underline block mt-1">🌐 www.aichainzom</a>
                        </section>
                    </div>

                    <section className="border-t border-white/10 pt-6 mt-6">
                        <h3 className="text-lg font-bold text-white mb-2"><span className="text-[#d4af37]">12.</span> Contact & Support</h3>
                        <p className="text-sm text-gray-400">For any questions related to this policy, subscriptions, or technical support:</p>
                        <a href="mailto:support@win365.com" className="text-[#d4af37] font-bold hover:underline block mt-2">📧 support@win365.com</a>
                    </section>

                </div>

                {/* Footer */}
                <div className="p-4 border-t border-white/5 bg-black flex justify-center">
                    <button
                        onClick={onClose}
                        className="px-8 py-2 bg-gray-800 text-white font-bold uppercase tracking-wider rounded text-sm hover:bg-gray-700 transition-colors"
                    >
                        I Understand & Agree
                    </button>
                </div>
            </div>
        </div>
    );
};

export default LegalPolicyModal;
